#!/bin/sh

# Helper script for building from Git, without needing to `guix pull`.

GUILE_LOAD_COMPILED_PATH="$(pwd -P)${GUILE_LOAD_COMPILED_PATH:+:}$GUILE_LOAD_COMPILED_PATH"
GUILE_LOAD_PATH="$(pwd -P)${GUILE_LOAD_PATH:+:}$GUILE_LOAD_PATH"
export GUILE_LOAD_COMPILED_PATH GUILE_LOAD_PATH

exec "$@"
