#+TITLE: guix-cwl
#+OPTIONS: toc:nil num:nil

This is a GNU Guix [[https://www.gnu.org/software/guix/manual/en/html_node/Channels.html][channel]] for the Common Workflow Language which
can be installed on any Linux distribution (Guix is distribution
agnostic).

We also provide a ready made Docker container so you can run without
GNU Guix.

This package is used in my reproducible [[https://gitlab.com/pjotrp/guix-notes/blob/master/WORKFLOW.org][WORKFLOW]] example.

* How to use

** With Docker

Requirements: Docker

tbd

** With GNU Guix channel

Requirements: Guix >= 0.16 (for the /channel/ feature)

On Ubuntu, Debian, Redhat etc., after installing the [[https://www.gnu.org/software/guix/download/][GNU Guix 0.16.0
Binary]] and following the [[https://www.gnu.org/software/guix/manual/en/html_node/Binary-Installation.html][instructions]] to create a build user etc.,
create or modify the =~/.config/guix/channels.scm= file so it includes

#+BEGIN_SRC scheme

;; Add my personal packages to those Guix provides.
(cons (channel
        (name 'guix-cwl)
        (url "https://github.com/genenetwork/guix-cwl.git"))
      %default-channels)
#+END_SRC

Then run ~guix pull~ as usual and a =cwltool= package is available:

: guix pull

Right after you should be able to see the channel with

: Updating channel 'guix-cwl' from Git repository at 'https://github.com/genenetwork/guix-cwl.git'...
: Updating channel 'guix' from Git repository at 'https://git.savannah.gnu.org/git/guix.git'...
: Building from these channels:
:   guix-cwl  https://github.com/genenetwork/guix-cwl.git ac394cf
:   guix      https://git.savannah.gnu.org/git/guix.git   cf51b82

and the package

: guix package -A cwltool

It may take a while to download these packages and some may need to be
built. For more ready made binary substitutes you can try instead

: guix pull --substitute-urls="https://berlin.guixsd.org http://guix.genenetwork.org https://mirror.hydra.gnu.org"

and install (optionally use =--substitute-urls= again)

: ~/.config/guix/current/bin/guix package -i cwltool -p ~/opt/cwl

Now to run the tool you need to set the paths etc with

: . ~/opt/cwl/etc/profile
: cwltool --help

renders

: cwltool-1.0.20181012180214

** With GNU Guix GUIX_PACKAGE_PATH

There is no magic in channels. I.e., you can opt for the GUIX_PACKAGE_PATH from a checked out
GNU Guix repo. E.g.

: env GUIX_PACKAGE_PATH=../../gnu/channels/guix-cwl/ ./pre-inst-env guix package -i cwltool -p ~/opt/cwl

* Notice

This channel exists because not all dependencies are ready to go into
GNU Guix trunk and both CWL and schema-salad still use the older
typing_extensions. We ought to make CWL part of GNU Guix proper in
time.

Enjoy,

Pjotr Prins
