#+TITLE: guix-cwl
#+OPTIONS: toc:nil num:nil

This is a GNU Guix /channel/ for the Common Workflow Language which
can be installed on any Linux distribution (Guix is distribution
agnostic).

We also provide a ready made Docker container so you can run without
GNU Guix.

* How to use

** With Docker

tbd

** With GNU Guix channel

On Ubuntu, Debian, Redhat etc., after installing the [[https://www.gnu.org/software/guix/download/][GNU Guix 0.16.0
Binary]] and following the [[https://www.gnu.org/software/guix/manual/en/html_node/Binary-Installation.html][instructions]] to create a build user etc.,
create or modify the =~/.config/guix/channels.scm= file so it includes

#+BEGIN_SRC scheme
(cons (channel
        (name 'guix-cwl)
        (url "https://github.com/pjotrp/guix-cwl.git")
        (branch "master"))
      %default-channels)
#+END_SRC

Then run ~guix pull~ as usual and a =cwltool= package is available:

: guix pull
: guix package -A cwltool

For more ready made binary substitutes you can try instead

: guix pull --substitute-urls="https://berlin.guixsd.org http://guix.genenetwork.org https://mirror.hydra.gnu.org"

** With GNU Guix GUIX_PACKAGE_PATH

There is no magic in channels. I.e., you can opt for the GUIX_PACKAGE_PATH from a checked out
GNU Guix repo. E.g.

: env GUIX_PACKAGE_PATH=../../gnu/channels/guix-cwl/ ./pre-inst-env guix package -i cwltool -p ~/opt/cwl

* Requirements

  * Guix > 0.15 (for the "channels" feature)

* Notice

This channel exists because not all dependencies are ready to go into
GNU Guix trunk. We ought to make CWL part of GNU Guix proper in time.

Pjotr Prins
