# -*- mode: org; coding: utf-8; -*-
#+TITLE: guix-cwl

A /reproducible/ from source build of =cwltool=.

This repository is a GNU Guix [[https://www.gnu.org/software/guix/manual/en/html_node/Channels.html][channel]] for the Common Workflow Language
which can be installed on any Linux distribution (Guix is distribution
agnostic). It also provide a ready made Docker container so you can
run without GNU Guix.

#+ATTR_HTML: :style margin-left: auto; margin-right: auto; width=100%;
[[http://biogems.info/cwltool-references.svg]]

This is the runtime graph including a recent version of Python. The
figure was generated with

: guix graph --type=references cwltool |dot -Tsvg > cwltool-references.svg

This package is used in the reproducible [[https://gitlab.com/pjotrp/guix-notes/blob/master/WORKFLOW.org][WORKFLOW]] example.

* Table of Contents                                                     :TOC:
 - [[#install-cwltool][Install cwltool]]
   - [[#with-docker][With Docker]]
   - [[#with-gnu-guix-channel][With GNU Guix channel]]
   - [[#with-guix_package_path][With GUIX_PACKAGE_PATH]]
 - [[#license][License]]
 - [[#notice][Notice]]

* Install cwltool

** With Docker

Requirements: Docker

GNU Guix can create Docker containers. For examples see [[https://gitlab.com/pjotrp/guix-notes/blob/master/CONTAINERS.org][here]].

The current container was created with

#+BEGIN_SRC bash
guix pack -f docker -S /usr/bin=/bin -S /etc/profile=/etc/profile cwltool
successfully built /gnu/store/mrwfvb02k9xxzmdfnspxbh4mxa9yg5np-docker-pack.tar.gz.drv
/gnu/store/4al6wg6crp6s3ykkhaz2c5ihrhxm50q3-docker-pack.tar.gz

ls -lh /gnu/store/4al6wg6crp6s3ykkhaz2c5ihrhxm50q3-docker-pack.tar.gz -h
-r--r--r-- 2 root root 198M Jan  1  1970 /gnu/store/4al6wg6crp6s3ykkhaz2c5ihrhxm50q3-docker-pack.tar.gz
#+END_SRC

The container only includes cwl and its dependencies (see above
figure)! You may want to add add binutils bash vim to be able to navigate inside
the container with

#+BEGIN_SRC bash
guix pack -f docker -S /usr/bin=/bin -S /etc/profile=/etc/profile \
   cwltool binutils bash vim
#+END_SRC

Load the docker image with

#+BEGIN_SRC bash
docker load --input /gnu/store/4al6wg6crp6s3ykkhaz2c5ihrhxm50q3-docker-pack.tar.gz
docker images
REPOSITORY          TAG                                IMAGE ID            CREATED             SIZE
profile             2g9kac4lj9cbfa5yqn687ds0rmmlfpj1   01c69b34c117        49 years ago        645 MB
#+END_SRC

You can ignore the time stamp. Run cwltool:

: docker run 01c69b34c117 /usr/bin/cwltool

The Docker image is available on Dockerhub as
https://cloud.docker.com/repository/docker/pjotrpublic/cwltool-1.0.20181012180214

Note that a bare image is useless because it does not include any of your workflow tooling. For example
running a cwltool example will complain about a missing 'echo' command:

#+BEGIN_SRC bash
docker run -v `pwd`:/app -w /app 01c69b34c117 /usr/bin/cwltool tests/echo.cwl --inp "test"
/gnu/store/dxr1rfmnq1wkq3fm97bbznnwarndlvrx-cwltool-1.0.20181012180214/bin/.cwltool-real 1.0
Resolved 'tests/echo.cwl' to 'file:///app/tests/echo.cwl'
[job echo.cwl] /app/50olq6f5$ echo \
    test > /app/50olq6f5/out.txt
'echo' not found: [Errno 2] No such file or directory: 'echo': 'echo'
#+END_SRC

To run the workflow you'll need to add the required tools to the Docker image.
See the reproducible [[https://gitlab.com/pjotrp/guix-notes/blob/master/WORKFLOW.org][WORKFLOW]] example.

** With GNU Guix channel

Requirements: Guix >= 0.16 (for the /channel/ feature)

On Ubuntu, Debian, Redhat etc., after installing the [[https://www.gnu.org/software/guix/download/][GNU Guix 0.16.0
Binary]] and following the [[https://www.gnu.org/software/guix/manual/en/html_node/Binary-Installation.html][instructions]] to create a build user etc.,
create or modify the =~/.config/guix/channels.scm= file so it includes

#+BEGIN_SRC scheme

;; Add my personal packages to those Guix provides.
(cons (channel
        (name 'guix-cwl)
        (url "https://github.com/genenetwork/guix-cwl.git"))
      %default-channels)
#+END_SRC

Then run ~guix pull~ as usual and a =cwltool= package is available:

: guix pull

Right after you should be able to see the channel with

: Updating channel 'guix-cwl' from Git repository at 'https://github.com/genenetwork/guix-cwl.git'...
: Updating channel 'guix' from Git repository at 'https://git.savannah.gnu.org/git/guix.git'...
: Building from these channels:
:   guix-cwl  https://github.com/genenetwork/guix-cwl.git ac394cf
:   guix      https://git.savannah.gnu.org/git/guix.git   cf51b82

#+BEGIN_COMMENT

Note the git checkout hash cf51b82 is shown. With guix pull it is possible to fetch an
exact commit of the guix tree on savannah. That means the channel can be exactly reproduced with

: guix pull --commit=cf51b828af5358c1303bbb797f58433dd8d4c043

To see the installed generations

: guix pull --list-generations

E.g.

#+BEGIN_SRC

Generation 10   Dec 27 2018 02:14:05    (current)
  guix-cwl 2253446
    repository URL: https://github.com/genenetwork/guix-cwl.git
    branch: master
    commit: 2253446384d9fbe4f96e9d2e0f87fd8c5cd513d5
  guix 6286880
    repository URL: https://git.savannah.gnu.org/git/guix.git
    branch: master
    commit: 6286880a8b6cc2b3ad8a92dd9d2067842b55f936
  1 new package: badvpn
  3 packages upgraded: kodi@18.0rc3, python-schema-salad@3.0.20181206233650, terminology@1.3.2
#+END_SRC

#+END_COMMENT

After the pull the package should be visible

: guix package -A cwltool

It may take a while to download these packages and some may need to be
built. For more ready made binary substitutes you can try instead

: guix pull --substitute-urls="https://berlin.guixsd.org http://guix.genenetwork.org https://mirror.hydra.gnu.org"

and install (optionally use =--substitute-urls= again)

: guix package -i cwltool -p ~/opt/cwl

Now to run the tool you need to set the paths etc with

: . ~/opt/cwl/etc/profile
: cwltool --help

renders

: cwltool-1.0.20181012180214

** With GUIX_PACKAGE_PATH

There is no magic in channels. I.e., you can opt for the GUIX_PACKAGE_PATH from a checked out
GNU Guix repo. E.g.

: env GUIX_PACKAGE_PATH=../../gnu/channels/guix-cwl/ ./pre-inst-env guix package -i cwltool -p ~/opt/cwl

* License

This channel is published under the GPLv3 in line with other
[[https://www.gnu.org/software/guix/packages/][GNU Guix package definitions]].

* Notice

This guix-cwl channel exists because not all dependencies are ready to
go into GNU Guix trunk and both CWL and schema-salad still use the
older typing_extensions which obsolete with Python 3.7. We ought to
make CWL part of GNU Guix proper in time.

Enjoy,

Pjotr Prins
